
# **ESS 314: Lab 1**

This is the first lab of ESS 314. The lab was designed by Ken Creager, Harold Tobin, and modified by Anna Ledeczi (ledeczi@uw.edu) and Marine Denolle (mdenolle@uw.edu)


## **Lab 1A: Setting up Your Workspace**


This lab focuses on helping students set up their workspace so that they can access the relevant
software packages necessary for future lab work. *You do not need to turn anything in for portion 1A of the lab.*



 ### **Computer Resources**

1. ***UW-JupyterHub***

UW-IT set up a jupyterhub for our course. You can start one with the following link in your browser:

https://rttl.axdd.s.uw.edu/2021-autumn-ess-314-a

You will need UW ID credentials to get started. You can log in from the ESS Lab computers and from your laptop.

You will be prompted to a Jupyter Notebook in Python. We thrive to use open-source python codes that should be available through our python environment or easy to install using simple commands.



**Now, we will go through an example on how to get the hub ready**.

* Log in to the server
* To add files, you can click the upload button on the top and upload individual files and folters.
* To add the git repos with the scripts and lab notebook, open a terminal window and type ``git clone "https://github.com/UW-geophysics-edu/ESS314-fall21.git"``. The entire updated github repository will be transfered to your environments.
* The files that you add to the environment will be saved and left as is for future times.
* To update the github repository. Open a terminal, move into the directory using the command ``cd ~/ESS314-fall21``, and type ``git pull``. This will update your directory with the updated version of the remote class github.


2. ***Google Colab***

Google Colab is a free python notebook environment. It comes in with a built-in python environment. Once you open a notebook in Colab, click ``Connect`` on the top right, select ``Connect to a hosted runtime`` to launch your instance on the free Google Cloud Platform.

To add packages, just use the following command everytime you log in, for instance:

``!pip install mypackage``



3. ***Your own Local Python***

We created an conda environment in the class Github Page: https://github.com/UW-geophysics-edu/ess314-2021-image.
Similar to the hub, open a terminal window. Move to the directory of choice and type:

*  ``git clone "https://github.com/UW-geophysics-edu/ESS314-fall21.git"``.
 
* Move into the directory: ``cd ESS314-fall21``
* Create the conda environment: ``conda env create -f environment.yml``
* start the conda environment: ``conda activate ess314``

Now you are ready to do some pythoning!



### **Getting Familiar with Shell scripting**

Shell scripting allows you to navigate through your computer directories, files, and perform basic manipulation of text files. It can also allows you to run big simulations on large computers. It is extremely flexible!

Start by opening a **Terminal** window. The basic commands you will need are:

* ``pwd`` to see what directory you are in.
* ``cd FOLDER`` to move to another directory
* ``cd ../OTHER_FOLDER`` to move to another directory that is ahead of your current directory. This provides a *relative* path.
* ``cd /home/user/whatever/your/path/is`` is you know the *absolute* path of the directory you want to go to.
* ``ls `` it will list all of the files in the current directory
* ``ls ./*``, exact same as above
* ``ls ../*``, will list the files in the directory ahead of your current directory
* ``mkdir NEW_DIRECTORY`` wil create a new directory
* ``cp file to_new_directory`` will copy ``file`` to another directory
* ``cp -r this_directory to_this_directory``, will copy a folder and everything within it into another directory.


We recommend to take the SoftwareCarpentry classes if you want to learn more. They have sometimes workshop through UW/eScience, or you can follow their lessons on Shell scripting here: 
https://swcarpentry.github.io/shell-novice/


### **Getting Familiar with Git**


Github is becoming a fundamental tool in STEM education and research. It allows you to keep track of code versions, without having to save a file per version. It also allows you to share your work, share your code, and work as a team very efficiently. 

Github has a web-platform: https://github.com/

Our class Github is here: https://github.com/UW-geophysics-edu/ESS314-fall21


Github toolbox is installed on the JupyterHub. You may already have it installed on your local machine (lapto/desktop), or you may have to install it. Follow the instructions here: https://github.com/git-guides/install-git

A cheat sheet of commands is added on Canvas and on the github website. 

You can just download all courses labs and scripts through the Github website as the repository is public. If you wish to create your own repository for this class and upload your own codes:
* create a Github account (I advise using your uwnet ID or an EASY identifier).
* Follow guidelines from the cheat sheet to use command line to navigate through git.


Further master your Git Skills by taking the basic lesson from the Software Carpentry: https://swcarpentry.github.io/git-novice/. 

## **Lab 1B: Introduction to Python**

Python is an increasingly common scientific tool which we will be utilizing in this course. Lab 1B focuses on gettnig acquainted with Python basics.

*Questions/Items for submission are shown in italics. For all questions, show the command you used to arrive at the answer.*

**Setting Variables**

 
2.   Many basic commands are available in Python, including arithmetic functions. For example, type 2+2 into a code cell and press SHIFT+ENTER.

In [ ]:
2+2

4

3. Arithmetic operators are + for addition, - for subtraction, * for multiplication, and / for division. Raising a value to a power is accomplished by using ** (e.g. 3**2).

4. Type a=2 into the next cell. This will assign the value 2 to the variable a, which will hold this value until it is reassigned. To reassign a, type a=3 in the next cell.

In [ ]:
a = 2 # Make sure to add comments to your code as you go to ensure clarity

In [ ]:
a = 3 # Here you could remark on what the variable a represents in your code

5. Assign a value to b. Now type c = a+b and Python will calculate the value of c. Note that Python will not print out the result of c automatically unless it is told to do so. To see the value of c, type print(c). 

In [ ]:
b = 4
c = a + b
print(c)

7


6. There are several kinds of variables in Python. Numbers can be integers, like a, whole numbers without a decimal point. Numbers designated as float have a decimal value. For computational purposes, float numbers are more useful. Python also allows the designation of text, or 'strings' as variables. Type d = 7.2 and e = 'hello!' to utilize float and string variables.

In [ ]:
d = 7.2
e = 'hello!'

7. To see all variables, their type, and their value, use the command %whos. Deleting a single variable can be accomplished using the command del following by the desired variable (e.g., del a). To delete all defined variables, use %reset. Check if the deletions were successful using %whos.

In [ ]:
del a 
%whos

Variable   Type     Data/Info
-----------------------------
b          int      4
c          int      7
d          float    7.2
e          str      hello!


8. It is important to note that variables in Python can consist of numbers, upper and lowercase letters, and underscores. A variable name cannot start with a number. Variable names are generally more useful when they are more descriptive (e.g., gravity_anomaly rather than ga). 

### **Question 1:**



> ***a.*** What command would be used to clear just the b variable?*





answer below:



> ***b.*** What command would be used to clear all variables?*


answer below:



> ***c.*** Which of the following are valid variable names?*
* *_n*
* *n6*
* *n_*
* *6n*
* *nnnnnnnnnnnnnnnnnnnnn*


answer below:


> ***d.*** *What error message appears when you try to use an invalid variable name?*

answer below:

**Basic Commands and NumPy**





1.   In order to perform more advanced calculations, certain Python packages must be imported. For example, numerical python is a key package. To import this, use the command 






In [ ]:
import numpy as np

2. To use numpy, commands must begin with np. For example, type np.pi and you will see the result printed to the screen. To round this number to a certain number of decimal places, assign the result to a variable, then use the function round, for example:


In [ ]:
pi = np.pi
round(pi, 2)

3.14

3. In numpy, log(x) calculates the natural log of a number. log10(x) will return the log base 10 and log2(x) will return the log base 2. 


In [ ]:
np.log10(10)

1.0


4. The command np.sqrt() can be used to calculate the square root of positive numbers.


In [ ]:
np.sqrt(3)

1.7320508075688772


5. Trigonometric functions in NumPy take angles in radians, so make sure your input angles are not in degrees. You can also use the built-in NumPy conversion between degrees and radians.

In [ ]:
print(np.sin(np.pi/2))
print(np.sin(np.deg2rad(90))) # You can also use np.rad2deg() for other calculations

1.0
1.0


6. Inverse trigonometric functions can be calculated using np.arcsin(), np.arccos(), and np.arctan().

In [ ]:
print(np.arcsin(np.sin(np.pi/3)))
print(np.pi/3)

1.0471975511965976
1.0471975511965976


### **Question 2:**

> ***a.*** *What is the command to return the value of e (Euler’s number)?*


In [ ]:
# answer below

> ***b.*** *What is the sin of 270 degrees?*

In [ ]:
# answer below

> ***c.*** *What is arccos(0.5) in degrees?*

In [ ]:
#answer below

> ***d.*** *What is arccos(0.5) in radians?*

In [ ]:
# answer below

**Vectors and Matrices**

NumPy can be utilized to create "arrays," which function as vectors or matrices. The size of a matrix with r rows and c columns is 𝑟 × 𝑐. Think of a row vector as a matrix with 𝑟 = 1, and a column vector as a matrix with 𝑐 = 1.



1.   Use the command np.array() to create row and column vectors as follows:


In [ ]:
row_vector = np.array([[1, 2, 3]])
print(row_vector)

col_vector = np.array([[1], [2], [3]])
print(col_vector)

# You can check that these vectors are indeed the dimensions you seek by using the following command:

print(row_vector.shape) # Should be (1, 3) for (r, c)
print(col_vector.shape) # Should be (3, 1) for (r, c)


[[1 2 3]]
[[1]
 [2]
 [3]]
(1, 3)
(3, 1)


2. Selecting specific values in a vector or matrix is known as indexing. Start by creating a 3 x 4 matrix as follows.

In [ ]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


To select elements within the matrix, specify their location within the rows and columns, making sure to begin counting at 0. If you are used to MATLAB, it is important to remember that Python indexing starts at 0, not 1. Here are some examples of indexing:

In [ ]:
print(matrix[1,2]) # The number 7
print(matrix[2,0]) # The number 9
print(matrix[0, :]) # The first row
column1 = matrix[:, 0] # The first column - but note it only has one dimension
print(column1)
column1.shape # but note it only has one dimension and is not technically a 'row' or 'column'

matrixT = np.transpose(matrix) # Transpose a matrix using this command
print(matrixT)


7
9
[1 2 3 4]
[1 5 9]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


3. There are other ways to create more specialized kinds of arrays, such as those made out of zeroes, ones, or a linearly spaced array.

In [ ]:
print(np.zeros([3,1]))

print(np.ones([4,1]))

print(np.linspace(0,10,5)) # Specify start, stop, and the number of elements for a linearly spaced array

print(np.arange(0, 10, 2)) # Specify start, stop, and spacing



# Note the difference between the following: 

print(np.linspace(0,10,10))
print(np.linspace(0,10,11))

[[0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]
 [1.]]
[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


4. You can concatenate or truncate vectors once they are created. The two arrays must have the same shape, except in the direction of the axis. 

In [ ]:
g = np.ones([4,3])
print(g)

h = np.zeros([2,3])
print(h)

i = np.concatenate((g,h)) # axis is assumed 0 unless specified 
print(i)


j = np.ones([1,2])
print(j)

k = np.zeros([1, 3])
print(k)

l = np.concatenate((j, k), axis=1)
print(l)

m = np.concatenate((k, j), axis=1) # reverses the order from above
print(m)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]
[[0. 0. 0.]]
[[1. 1. 0. 0. 0.]]
[[0. 0. 0. 1. 1.]]


In [ ]:
# Use these for Question 3

v = np.array([[1, 2, 3]])
w = np.array([[1], [2], [3]])


### **Question 3:**

> ***a.*** *What is the difference between v and w?*



answer here


> ***b.*** *Explain the function of np.transpose().*


answer here

> ***c.*** *Create a matrix with three columns, each of which is a copy of vector w*

In [ ]:
#answer below

> ***d.*** *Select the entire third column of the matrix you just created?*

In [ ]:
#answer below

**Operations with Vectors and Matrices**



In [ ]:
v = np.array([[1, 2, 3]])
w = np.array([[1], [2], [3]])
p = ([[3, 4, 5, 6]])
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
N = np.concatenate((v, v, v))

1. Adding a scalar to a vector or matrix is the same as adding two scalar values. Similarly,
multiplying a vector or matrix by a scalar value looks just like multiplying two scalars.
a. To add 2 to all elements of your vector v, type v+2.
b. To multiply each element of matrix M by 3, type M*3.

In [ ]:
print(v+2)
print(M*3)

[[3 4 5]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


2. Adding two matrices may work differently than you expect. Try adding v+N and p+N.

In [ ]:
v+N

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [ ]:
p+N

ValueError: ignored

3. To perform matrix multiplication, just multiply the two matrices by each other. Recall
that to multiply two matrices together, the number of columns in the first must equal
the number of rows in the second.
a. Try multiplying vector v by vector w. Make sure and show that they have the complementary dimensions.

In [ ]:
print(v.shape)
print(w.shape)
v*w

(1, 3)
(3, 1)


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

4. For square matrices, you can also raise the matrix to a power using the same function as
you did with scalar values. Square the matrix M using the command M**2, then review
the output.

In [ ]:
M**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

5. Operations that apply to each element of the matrix individually are sometimes called array operations or element-wise operations. Many functions, such as trig functions, will operate on a matrix element-by-element. For example, try np.sin(N).

In [ ]:
np.sin(N)

array([[0.84147098, 0.90929743, 0.14112001],
       [0.84147098, 0.90929743, 0.14112001],
       [0.84147098, 0.90929743, 0.14112001]])

*Question 4:*



>  ***a.*** *Why do you get an error message when you multiply v*v *but not when you multiply v*w?



> ***b.*** *What does Python do when you ask it to add v+M? What about p+M? Describe as best you can from your own experiments the logic that Python uses to add two matrices together. Include any relevant errors that might occur.*

**Plotting**



1.   Plotting in Python requires importing another package, known as matplotlib. You can find tutorials and self-teach yourself about plotting in Python on the Matplotlib tutorial page: https://matplotlib.org/stable/tutorials/index.html



In [ ]:
import matplotlib.pyplot as plt # You will have to run this import cell each time you open the notebook

2. Create a row vector x with the numbers 1 through 50. Then, use the sine function to vector y where each element is the sine of the corresponding value in x.

In [ ]:
x = np.linspace(1,50,50)
y = np.sin(x)

3. Create a simple plot using matplotlib.

In [ ]:
fig = plt.plot(x,y, 'g:') # 'g:' defines the color (g) and the pattern (:) of the lines here. 
# You can search for color legends and more line patterns. - is a line, o is dots. 
plt.xlabel('x label')
plt.ylabel('y label')
plt.title("Example Plot 1")
plt.show()


4. Create a figure with 2 subplots.

In [ ]:
z = np.cos(x)

In [ ]:
fig, ax = plt.subplots(2,1) # control how many rows and columns here
ax[0].plot(x,y, 'r-', label='sin(x)')
ax[0].set_title('Example Plot 2a')
ax[0].set_xlabel('This is x (radians)')
ax[0].set_ylabel('Sine of x')
ax[0].legend()

ax[1].plot(x, z, 'bo', label='cos(x)')
ax[1].set_title('Example Plot 2b')
ax[1].set_xlabel('This is x (radians)')
ax[1].set_ylabel('Cosine of x')
ax[1].legend()



plt.tight_layout() # This will add space between your subplots (try commenting out this line!)
plt.show()


# Use the following command to save the image
plt.savefig('example2.png')

NameError: ignored

5. Redefine x with twice as many points (i.e., define x as a row vector from 1 to 50, but include points at every half integer). Try to plot x and y again. What's wrong?

In [ ]:
x = np.linspace(1,50,99)
fig = plt.plot(x, y, 'b-')

### **Question 5:**

> ***a.*** *Redefine y as appropriate. Keep iterating on the resolution of x and y until you're satisfied that the graph looks like a sine wave. Add a title and axis labels. Export the plot image as a png named fig5. Open it from a file management app (Finder on Mac, Explorer on Windows) so you can be aware of the idiosyncrasies of exporting an
image. Include the fig5.png export file with your assignment submission when you turn in this lab on Canvas.*


> ***b.*** *Create a row vector from 0 – 100, counting by 5s (i.e. [0 5 10 15 20 … 100])?*


> ***c.*** *Plot x and y with maroon upward-facing triangles?*


> ***d.*** *What was the command you used to define x for your last plot?*


### **Question 6:**


> ***a***. *Plot two functions on the same plot. Define a new row vector x where the values range from 1 to 40.*



> ***b.*** *Define a vector y that is equal to x^2 + 50cos(x + 4). Please express the cosine in radians.*




> ***c.*** *Define a vector z that is equal to 1.5(tan(y)). Please express the tangent in radians.*


> ***d.*** *Plot y vs. x and z vs. x on the same graph. First, open a figure. Plot the y function as a blue solid line, and the z function as a red dotted line.*

> ***e.*** *Add a title, and label the x and y axes ‘x’ and 'y(x) and z(y(x))’, respectively.*


> ***f.*** *Plot more than one function on the same graph.*

> ***g.*** *Save the plot image as a png named fig6. You'll need to include this file in your submission for this lab.*